Noroff-Online-Team/noroff-api

- .gitignore
- package.json
- src/modules/social/posts/posts.controller.ts
- src/modules/social/posts/posts.schema.ts
- src/modules/social/profiles/profiles.controller.ts
- src/modules/social/profiles/profiles.schema.ts
- src/utils/mediaGuard.ts
- yarn.lock
Adds an async mediaGuard method that will throw if the image cannot be accessed via a simple get request
Closes #7
> Media validation

- package.json
- prisma/migrations/20221031120527_auction/migration.sql
- prisma/migrations/20221031140202_auction/migration.sql
- prisma/migrations/20221031145347_auction/migration.sql
- prisma/migrations/20221031145559_auction/migration.sql
- prisma/migrations/20221102170300_auction/migration.sql
- prisma/schema.prisma
- src/config/swagger.ts
- src/modules/auction/auth/auth.controller.ts
- src/modules/auction/auth/auth.route.ts
- src/modules/auction/auth/auth.schema.ts
- src/modules/auction/auth/auth.service.ts
- src/modules/auction/listings/listing.utils.ts
- src/modules/auction/listings/listings.controller.ts
- src/modules/auction/listings/listings.route.ts
- src/modules/auction/listings/listings.schema.ts
- src/modules/auction/listings/listings.service.ts
- src/modules/auction/profiles/profiles.controller.ts
- src/modules/auction/profiles/profiles.route.ts
- src/modules/auction/profiles/profiles.schema.ts
- src/modules/auction/profiles/profiles.service.ts
- src/modules/social/posts/posts.route.ts
- src/modules/social/profiles/profiles.route.ts
- src/server.ts
- yarn.lock
Adds Auction House endpoints.
- Authentication
- Profiles
- Listings
Closes #28
Closes #29 
Closes #30 
There's also a [docs PR](https://github.com/NoroffFEU/noroff-api-docs/pull/10)
> Add Auction House

- src/modules/social/posts/posts.controller.ts
- src/modules/social/posts/posts.route.ts
- src/modules/social/posts/posts.service.ts
- Adds `GET /social/posts/following` with ability to get posts only for profiles you follow.
Closes #40
> Get posts only for profiles you follow

- src/modules/auction/listings/listings.schema.ts
- Added limit of 280 characters for title
- Added limit of 280 characters for description
- Added limit of 8 tags
- Added limit of 8 images
Closes #48
> Limit title, description, tags and media length of auction listings

- src/server.ts
- Adds custom `keyGenerator` method to rate-limit package.
> Add rate-limit keyGenerator

- prisma/migrations/20230102124214_online_shop/migration.sql
Adds the missing SQL migration file for the new `online-shop` routes
> Add missing sql migration file

- src/modules/auction/profiles/profiles.schema.ts
- src/modules/social/profiles/profiles.schema.ts
Regex pattern should now only allow for .no in top-level domain.
> Fixes issue with auction email regex pattern

- prisma/migrations/20230421130130_holidaze_location_and_rating/migration.sql
- prisma/schema.prisma
- src/modules/holidaze/venues/venues.schema.ts
- src/modules/holidaze/venues/venues.service.ts
- Adds rating 0-5 number as float
- Adds location object with `address`, `city`, `zip`, `country`, `continent` properties
> feat/holidaze: Add rating and location

- prisma/migrations/20230422130229_holidaze_add_latlng/migration.sql
- prisma/schema.prisma
- src/modules/holidaze/venues/venues.schema.ts
- Adds `lat` and `lng` properties inside `location` of venues.
> feat/holidaze: Add lat, lng

- src/modules/holidaze/bookings/booking.service.ts
- src/modules/holidaze/profiles/profiles.service.ts
- Some requests were missing the location of a venue and lead to Zod errors for not satisfying return schema.
> fix/holidaze: Return venue location

- src/modules/holidaze/profiles/profiles.service.ts
Imagine missing one even after you double-check you got them all.
> fix/holidaze: Return venue location v2 - I'm an idiot

- src/modules/holidaze/profiles/profiles.controller.ts
- src/modules/holidaze/profiles/profiles.route.ts
- src/modules/holidaze/profiles/profiles.schema.ts
- src/modules/holidaze/profiles/profiles.service.ts
- Adds `PUT /holidaze/profiles/:name` route that accepts `{ venueManager: boolean }` body
- Adds check for a valid profile to `PUT /holidaze/profiles/:name/media`
Closes #107
> Add ability to update venueManager bool

- src/modules/holidaze/profiles/profiles.controller.ts
- Add missing auth guards for updating profile and profile media
> Add missing auth guards for updating profile and profile media

- .github/workflows/v2_build_and_test.yml
- Adds build step to GitHub actions workflow
> Update action workflow to include build

- .github/workflows/docs_build.yml
- .github/workflows/v1_build.yml
- .github/workflows/v2_build_and_test.yml
Adds build workflow tests for v1 and docs.
> Add new workflows

- .eslintrc.js
- apps/docs/app/docs/[version]/layout.tsx
- apps/docs/app/global.css
- apps/docs/app/layout.tsx
- apps/docs/app/page.tsx
- apps/docs/app/provider.tsx
- apps/docs/components/nav.tsx
- apps/docs/components/search.tsx
- apps/docs/package.json
- yarn.lock
- Upgrade `next-docs-ui` and `next-docs-zeta`
- Update SearchDialog component to match new version
- Remove unused `katex` package
- Various smaller styling changes/fixes.
> Various docs work

- apps/v1/package.json
- apps/v2/package.json
- yarn.lock
Use `tsx` for dev scripts. Leave `tsup` for build.
> Use tsx for dev scripts

- apps/v1/src/modules/auction/profiles/profiles.controller.ts
- apps/v1/src/modules/social/profiles/profiles.controller.ts
Adds check for profile + is owner for updating media on social and auction profile
> fix: v1 auth checks

- apps/v1/prisma/schema.prisma
- apps/v1/src/modules/social/posts/posts.controller.ts
- apps/v1/src/modules/social/posts/posts.route.ts
- apps/v1/src/modules/social/posts/posts.schema.ts
- apps/v1/src/modules/social/posts/posts.service.ts
- Adds `DELETE /social/posts/:postId/comment/:commentId` route that will delete a particular post comment and all of its replies
> feat: Delete social post comment & replies

- apps/docs/content/docs/v1/social/posts.mdx
Adds a section in v1 docs on deleting comments from social posts.
> docs: add section on delete post comment

- apps/docs/content/docs/v2/social/posts.mdx
- apps/v2/docker-compose.tests.yml
- apps/v2/src/modules/social/posts/__tests__/createOrDeleteReaction.test.ts
- apps/v2/src/modules/social/posts/posts.schema.ts
- apps/v2/src/modules/social/posts/posts.service.ts
- Include reactor usernames in array of each post reactions.
- Also optimize the logic behind this.
- Update docs to match new reaction schema.
- Fix docker-compose syntax error.
> Social posts - include reactor usernames

- apps/v2/src/modules/auction/profiles/profiles.service.ts
> fix incorrect bidder schema for auction/profile/:name/listings

- apps/docs/components/api-key-tool.tsx
- apps/docs/components/ui/button.tsx
- apps/docs/components/ui/card.tsx
- apps/docs/components/ui/input.tsx
- apps/docs/components/ui/label.tsx
- apps/docs/components/ui/tabs.tsx
- apps/docs/content/docs/v2/auth/api-key.mdx
- apps/docs/package.json
- package.json
- pnpm-lock.yaml
Adds a client side API key generator for students here: https://docs.noroff.dev/docs/v2/auth/api-key#api-key-tool
> Api key tool

- apps/docs/Dockerfile
- apps/v1/Dockerfile
- apps/v2/Dockerfile
- package.json
- Updates docker and project to rely on latest node 22 release.
- Node 22.14 includes a fix for a corepack issue that sometimes crashes and fails on build in prod
> update to node22

- apps/docs/content/docs/v2/meta.json
- apps/docs/content/docs/v2/pets.mdx
- apps/docs/tsconfig.json
- apps/v2/package.json
- apps/v2/prisma/migrations/20250311145224_add_pets/migration.sql
- apps/v2/prisma/migrations/20250311190007_pets_add_default_adoption_status_remove_optional/migration.sql
- apps/v2/prisma/migrations/20250312112215_pet_created_and_updated_fields/migration.sql
- apps/v2/prisma/schema.prisma
- apps/v2/src/modules/pets/__tests__/createPet.test.ts
- apps/v2/src/modules/pets/__tests__/deletePet.test.ts
- apps/v2/src/modules/pets/__tests__/getPet.test.ts
- apps/v2/src/modules/pets/__tests__/getPets.test.ts
- apps/v2/src/modules/pets/__tests__/updatePet.test.ts
- apps/v2/src/modules/pets/pets.controller.ts
- apps/v2/src/modules/pets/pets.route.ts
- apps/v2/src/modules/pets/pets.schema.ts
- apps/v2/src/modules/pets/pets.service.ts
- apps/v2/src/modules/routes.ts
Adds Pets endpoints
Adds Pets documentation
Closes #212
Closes #213 
Closes #214 
Closes #215 
Closes #216
> PE2: Pets endpoint + documentation
