Noroff-Online-Team/noroff-api

src/modules/books/books.service.ts
src/modules/catFacts/catFacts.service.ts
src/modules/jokes/jokes.service.ts
src/modules/nbaTeams/nbaTeams.service.ts
src/modules/oldGames/oldGames.service.ts
src/modules/quotes/quotes.service.ts
src/modules/social/auth/auth.service.ts
src/modules/social/posts/posts.service.ts
src/modules/social/profiles/profiles.service.ts

- Adds `await` keyword to all queries that interact with Prisma.
According to [this discussion](https://github.com/prisma/prisma/discussions/3781), it's required as the Prisma client is lazy, and only evaluates when `await` is called.

Add await to Prisma queries

---

src/modules/social/posts/posts.schema.ts
src/server.ts

- Removes `.url()` from post `_author` flag response schema.
- Makes sure at least one of title, body, tags or media is provided when updating a post.
- Makes `body` property optional when creating a post.
- Adds `ignoreTrailingSlash: true` to Fastify config. This will make sure both `/api/v1/books` and `/api/v1/books/` work, instead of throwing a 404 in some cases if you include the trailing slash.

Fix error validations

---

src/modules/social/posts/posts.service.ts
src/modules/social/profiles/profiles.controller.ts
src/modules/social/profiles/profiles.route.ts
src/modules/social/profiles/profiles.service.ts

- Adds a new `GET /social/profiles/:name/posts` endpoint to retrieve all posts by username.
- Return `postId` field after creating comment. This is in line with reacting and is also what docs specify.
[Related docs PR](https://github.com/NoroffFEU/noroff-api-docs/pull/9/files)

Get all posts by user

---

package.json
prisma/migrations/20221027084127_init_new_db/migration.sql

- Adds new Prisma migration file for new db. Realistically this just fixes cascade foreign keys with Prisma v4 upgrade.
- Removes `prestart` script.
- Initially this was just a shorthand to not require building manually. Render runs both the build and start scripts separately, which results in 2 builds and a extra long startup time. Removing this script should reduce PR merge->live time by ~50%.
- Adds `--exit-child` flag to `tsnd` for `dev` script. This will fix the need for restarting dev script manually when making changes locally, and instead will restart it automatically on save.

Init new db & misc

---

package.json
yarn.lock

- Upgrades node types to 18.11.9 to resolve conflicting definitions with node-schedule package.

Upgrade node types

---

prisma/migrations/20221115120500_auction/migration.sql
prisma/schema.prisma
src/modules/auction/listings/listings.controller.ts
src/modules/auction/listings/listings.schema.ts
src/modules/auction/listings/listings.service.ts

- Adds `tags` array to Auction listings.
- Adds `?_tag=x` flag to `GET /auction/listings` with ability to filter by tag.
Each listing can have multiple tags, but the `?_tag=` filter flag only accept filtering by a single tag.
For example: `GET /auction/listings?_tag=chuck_norris` will return all listings that includes a `chuck_norris` tag in its tags array.
Closes #34

Add Auction tags + filter for tag

---

prisma/migrations/20221117153858_auction/migration.sql
prisma/schema.prisma
src/modules/auction/listings/listing.utils.ts
src/modules/auction/profiles/profiles.schema.ts

- Adds `wins` property to AuctionProfile model. When you successfully win a listing, the listing uuid will be added here.

Add wins array to keep track of listings won

---

src/modules/social/posts/posts.controller.ts
src/modules/social/posts/posts.schema.ts
src/modules/social/posts/posts.service.ts

- Adds `?_tag=x` flag to `GET /social/posts` and `GET /social/posts/following` with ability to filter by tag.
Each post can have multiple tags, but the `?_tag=` filter flag only accept filtering by a single tag.
For example: `GET /social/posts?_tag=chuck_norris` will return all posts that includes a `chuck_norris` tag in its tags array.
Closes #44

Add _tag flag to Social posts

---

src/modules/social/posts/posts.schema.ts
src/modules/social/posts/posts.service.ts

- Adds the full author object of a comment author if `?_comments=true` flag is passed for posts. Previously only the comment owner name was returned. 
Old:
```json
"comments": [
{
"body": "A comment",
"replyToId": null,
"id": 1,
"postId": 3,
"owner": "jan",
"created": "2022-11-25T12:23:11.589Z"
}
]
```
New:
```json
"comments": [
{
"body": "A comment",
"replyToId": null,
"id": 1,
"postId": 3,
"owner": "jan",
"created": "2022-11-25T12:23:11.589Z",
"author": {
"name": "jan",
"email": "jan.teige@noroff.no",
"avatar": "https://picsum.photos/id/135/800/800",
"banner": "https://picsum.photos/id/474/1500/600"
}
}
]
```
Closes #43

Return author object for comments

---

src/modules/auction/listings/listing.utils.ts

Going through logs I noticed this was throwing errors sometimes. Seeing as listings can be deleted by its creator, it also makes sense to make sure it exists before we attempt to transfer credits.

Make sure listing exists when transferring credits

---

src/modules/auction/listings/listings.schema.ts
src/modules/auction/profiles/profiles.controller.ts
src/modules/auction/profiles/profiles.route.ts
src/modules/auction/profiles/profiles.service.ts

- Adds `GET /auction/profiles/:name/bids` endpoint that returns all bids made by profile. Also accepts `_listings` flag to return the listing for each bid.
Closes #39

Add ability to see bids by profile

---

src/modules/auction/listings/listings.controller.ts
src/modules/auction/listings/listings.schema.ts
src/modules/auction/listings/listings.service.ts
src/modules/auction/profiles/profiles.controller.ts
src/modules/auction/profiles/profiles.service.ts

- Adds `_active` flag to `GET /auction/listings` to return only active listings.
- Adds `_active` flag to `GET /auction/profile/<name>/listings` to return only active listings.
- Adds `_tag` flag to `GET /auction/profile/<name>/listings`  to return all listings from profile that include a certain tag in its tags array.
The `_active` flag was mentioned in #64.

Add _active flag to listings

---

src/modules/social/profiles/profiles.service.ts

We added the author object to comments in #52 but are not returning this when getting posts from on a certain profile. This PR fixes this. The code already exists from that PR, but was not being returned with this endpoint.
Closes #72

Add comment author to posts by profile

---

src/modules/auction/listings/listings.schema.ts
src/modules/social/posts/posts.schema.ts

- Adds a max of 24 characters per tag to Posts and Listings.
- Adds limit of 8 tags to Posts. This already exists for Listings.
- Refine media/image error message for consistency.
Closes #60

Tags max length

---

src/modules/auction/listings/listings.schema.ts
src/modules/social/posts/posts.schema.ts

`.length()` requires the exact to be sent, and does not allow for under or over the set number. `.max()` will allow for all numbers up to the specified.

Use z.max instead of z.length

---

src/modules/auction/listings/listings.schema.ts

With the new check for `date < today` we're reusing the `today` variable which has been changed from actually being "today" to a year in the future at the `oneYearFromToday` variable where we use `setFullYear()`. Therefore the actual comparison would never return true.

Fixed listing endsAt

---

apps/v1/package.json
apps/v2/jest.config.ts
apps/v2/package.json
apps/v2/src/modules/auction/listings/__tests__/createListing.test.ts
apps/v2/src/modules/auction/profiles/__tests__/getProfileWins.test.ts
apps/v2/tsconfig.json
packages/api-utils/package.json
yarn.lock

- Upgrades TypeScript to 5.2.2 from 4.8.2
- Downgrades Zod to 3.21.4 from 3.22.3 - seems to cause a build issue. Similar issues exists in TS and Zod repos so waiting for those to be resolved. Not related to TS upgrade.
- Sets a global jest `testTimeout` rather than specifying manually in multiple tests.

v2: Some package upgrades

---

apps/docs/content/docs/v1/social/posts.mdx
apps/docs/content/docs/v2/auction-house/listings.mdx
apps/docs/content/docs/v2/auction-house/profiles.mdx
apps/docs/content/docs/v2/holidaze/profiles.mdx
apps/docs/content/docs/v2/holidaze/venues.mdx
apps/docs/content/docs/v2/social/posts.mdx
apps/docs/content/docs/v2/social/profiles.mdx
apps/v2/src/modules/auction/profiles/profiles.route.ts

**Docs**
- Remove `_active` tag example in docs for social posts as it's incorrect.
- Adds docs for the new `/search` endpoint.
**API v2**
- Fixes incorrect swagger tag for auction profile `/search` endpoint.

docs/v2: misc updates + fixes

---

apps/v2/src/exceptions/errorHandler.ts

Adds some additional JWT error codes to the error handler check to return a better error than the default "Something went wrong".

Add more checks for JWT error codes

---

apps/docs/app/global.css
apps/docs/package.json
yarn.lock

Fixes `Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly.`
Also fixes wide layout for new next-docs-ui as it requires !important to override max-width.

docs: Add sharp as dep for standalone build

---

.prettierrc
package.json
yarn.lock

- Adds the `@ianvs/prettier-plugin-sort-imports` plugin to prettier, and adds `importOrder` in prettier config.
Another PR will follow which runs this and formats all apps and packages. This PR simply adds and configures it.

Add and configure prettier-plugin-sort-imports

---

apps/docs/content/docs/v2/social/posts.mdx
apps/v1/src/modules/social/posts/posts.controller.ts
apps/v2/prisma/migrations/20231121140951_cascade_delete_comment_with_replies/migration.sql
apps/v2/prisma/schema.prisma
apps/v2/src/modules/social/posts/__tests__/deleteComment.test.ts
apps/v2/src/modules/social/posts/posts.controller.ts
apps/v2/src/modules/social/posts/posts.route.ts
apps/v2/src/modules/social/posts/posts.schema.ts
apps/v2/src/modules/social/posts/posts.service.ts

v2: 
- Adds ability to delete comments from social posts through `DELETE /social/post/:postId/comment/:commentId`.
- Deleted comments also deletes replies to that comment. Similarly to how it works on v1.
- Adds docs for delete endpoint
v1: 
- Adds missing check for if the comment requesting to be deleted is related to the post from the same query.

v2/feat: Add delete social post comment

---

apps/docs/content/docs/v1/auction-house/listings.mdx

An oversight was made. I thought there was one block managing both versions but there was two. 
This adds fix to V1 spelling error.

Fix typo in v1 _bids_ property name

---

apps/docs/content/docs/v2/auction-house/profiles.mdx
apps/docs/content/docs/v2/holidaze/profiles.mdx
apps/docs/content/docs/v2/social/profiles.mdx
apps/v1/src/modules/auction/listings/listings.schema.ts
apps/v1/src/modules/index/index.route.ts
apps/v1/src/modules/social/posts/posts.schema.ts
apps/v1/src/server.ts
apps/v2/src/modules/auction/listings/listings.schema.ts
apps/v2/src/modules/auction/profiles/__tests__/updateProfile.test.ts
apps/v2/src/modules/auction/profiles/profiles.controller.ts
apps/v2/src/modules/auction/profiles/profiles.schema.ts
apps/v2/src/modules/auction/profiles/profiles.service.ts
apps/v2/src/modules/auth/auth.schema.ts
apps/v2/src/modules/holidaze/profiles/__tests__/updateProfile.test.ts
apps/v2/src/modules/holidaze/profiles/profiles.controller.ts
apps/v2/src/modules/holidaze/profiles/profiles.schema.ts
apps/v2/src/modules/index/index.route.ts
apps/v2/src/modules/routes.ts
apps/v2/src/modules/social/posts/posts.schema.ts
apps/v2/src/modules/social/profiles/__tests__/updateProfile.test.ts
apps/v2/src/modules/social/profiles/profiles.controller.ts
apps/v2/src/modules/social/profiles/profiles.schema.ts
apps/v2/src/modules/social/profiles/profiles.service.ts

Some fixes and updates. Decided to stick them all in a single PR.
- Adds ability to update user profile bio.
- Social post and auction listings now have 1 character min length requirement for titles. 
- I've fixed this for both v1 and v2 so they match.
- I have manually added "Default title" to any that didn't have a title in the database.
- Adds github, docs, and swagger links to the index route for both v1 and v2 APIs.
Closes #162
Closes #163
Closes #164

Update profile bio, min length for titles, index route info

---

apps/v1/src/hooks/onRequest.ts
apps/v2/src/hooks/onRequest.ts
docker-compose.dev.yml

Finally fixing this. The social follow/unfollow has no request body, and students are receiving a generic "something went wrong" error. We could return a more friendly error but I'd rather just allow these requests if the header was provided.
I've set up the onRequest hook to be extendable for both the method and route being targeted.
This fixes this error for both v1 and v2.
Also fixed some syntax errors in docker-compose.

Remove content-type header if PUT and no body for social follow/unfollow

---

apps/v2/src/modules/auth/__tests__/registerProfile.test.ts
apps/v2/src/modules/auth/auth.controller.ts
apps/v2/src/modules/auth/auth.schema.ts
apps/v2/src/modules/auth/auth.service.ts
apps/v2/src/modules/holidaze/bookings/bookings.schema.ts
apps/v2/src/modules/holidaze/venues/__tests__/createVenue.test.ts
apps/v2/src/modules/holidaze/venues/__tests__/updateVenue.test.ts
apps/v2/src/modules/holidaze/venues/venues.schema.ts

- Only sign JWT with name and email.
- Allow specifying `venueManager` when creating an account.
- Adds max length to URLs of 300 characters.
- Merges in changes from #171 and adds on to it
Closes #170

JWT signing, venueManager boolean, schema updates

---

apps/v2/src/modules/blog/posts/__tests__/getPost.test.ts
apps/v2/src/modules/blog/posts/__tests__/getPosts.test.ts
apps/v2/src/modules/blog/posts/posts.controller.ts
apps/v2/src/modules/blog/posts/posts.route.ts

- removes auth guard from `GET /:name` and `GET /:name/:id`
- updates tests to match

blog: remove auth guard from viewing posts

---

apps/docs/content/docs/v2/auth/login.mdx
apps/v2/src/modules/auth/__tests__/login.test.ts
apps/v2/src/modules/auth/auth.controller.ts
apps/v2/src/modules/auth/auth.route.ts
apps/v2/src/modules/auth/auth.schema.ts
apps/v2/src/modules/auth/auth.service.ts

- adds `_holidaze` optional query param to `POST /auth/login`. Returns the `venueManager` boolean if included.
- also adds test
- adds section for query params to login docs.
This also serves as a setup and gives us the ability to extend this to add similar optional params like `_social` and `_auctionhouse` in the future should we want/need to return more info on login.

feat/login: Add optional params to login

---

apps/v2/src/modules/auction/listings/listing.utils.ts

since we don't keep track of or store the id that node-scheduler gives back, we cannot remove/cancel a schedule. i think just returning early if the listing doesn't exist is fine.
closes #178

listings: early return if listing doesn't exist

---

apps/v1/src/modules/auction/listings/listings.schema.ts
apps/v1/src/modules/auction/profiles/profiles.schema.ts
apps/v1/src/modules/holidaze/profiles/profiles.schema.ts
apps/v1/src/modules/social/posts/posts.schema.ts
apps/v1/src/modules/social/profiles/profiles.schema.ts
apps/v2/src/modules/auction/listings/listings.schema.ts
apps/v2/src/modules/auth/auth.schema.ts
apps/v2/src/modules/blog/posts/posts.schema.ts
apps/v2/src/modules/social/posts/posts.schema.ts

with the old setup you could provide a string of `" "` and it would pass validation, because we are checking the length before we trim whitespaces. Submitting only `" "` would then become `""` before inserting to db (and be invalid according to the schema,) thus causing errors when validating the response.

trim before checking length of input

---

apps/v2/src/modules/social/posts/posts.controller.ts
apps/v2/src/modules/social/posts/posts.service.ts

We relied on the `id` property when doing a lookup of followed users, but the JWT does not include the `id` property. This was removed in #172 and this bug has existed for quite some time.
We should update the type assertion here from `as UserProfile` to `as Pick<UserProfile, "name" | "email">` as well.

fix: Use name for profile lookup

---

apps/v2/src/modules/auction/listings/listings.controller.ts
apps/v2/src/modules/auction/profiles/profiles.controller.ts
apps/v2/src/modules/auth/auth.controller.ts
apps/v2/src/modules/blog/posts/posts.controller.ts
apps/v2/src/modules/holidaze/bookings/bookings.controller.ts
apps/v2/src/modules/holidaze/profiles/profiles.controller.ts
apps/v2/src/modules/holidaze/venues/venues.controller.ts
apps/v2/src/modules/social/posts/posts.controller.ts
apps/v2/src/modules/social/profiles/profiles.controller.ts
apps/v2/tsconfig.json
apps/v2/types/api.ts

Follow-up of #200 
- Add custom `RequestUser` type, picking fields from `UserProfile` that matches JWT.
- Replace `as UserProfile` with `as RequestUser` where applicable.

Custom RequestUser type

---

.github/workflows/docs_build.yml
.github/workflows/v1_build.yml
.github/workflows/v2_build_and_test.yml

Separate out the install and build for each GH Action. This will speed up our CI as it will only process the required files and not run any pre or post scripts. 
This should also remove install errors related to v1 or v2 when working with docs, as an example.

Separate install and build per workflow

---

.github/workflows/v2_build_and_test.yml
apps/docs/Dockerfile
apps/docs/tsconfig.json
apps/v1/package.json
apps/v1/src/hooks/logger.ts
apps/v2/package.json
apps/v2/prisma/seed.ts
apps/v2/src/hooks/logger.ts
apps/v2/src/modules/auction/listings/__tests__/createListing.test.ts
apps/v2/src/modules/holidaze/bookings/__tests__/createBooking.test.ts
package.json
pnpm-lock.yaml
turbo.json

- Upgrade turbo to version 2
- Fixes docs dockerfile build by copying over required config file before build
- Remove unnecessary postinstall scripts from v1 and v2
- Fix type import in v2 prisma seed script.

Upgrade turbo, fix docs build
